baseURL = "https://monirsaikat.github.io/"
title = "Monir Saikat"
theme = "PaperMod"
[pagination]
  pagerSize = 10
enableRobotsTXT = true
defaultContentLanguage = "en"
languageCode = "en"

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
  env = "production"
  description = "Personal site, notes, and experiments by Saikat."
  author = "Saikat"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  defaultTheme = "auto"
  disableThemeToggle = false
  images = ["/assets/api.svg"] # used for social cards if no cover

  # Add your GitHub for the header icon
  socialIcons = [
    { name = "github", url = "https://github.com/monirsaikat" },
  ]

# Multilingual (English + Bengali)
[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    contentDir = "content/en"
    menu = { main = [
      { name = "Blog", url = "/en/", weight = 10 },
      { name = "Projects", url = "/en/projects/", weight = 20 },
      { name = "About", url = "/en/about/", weight = 30 }
    ]}

  [languages.bn]
    languageName = "বাংলা"
    weight = 2
    contentDir = "content/bn"
    menu = { main = [
      { name = "ব্লগ", url = "/bn/", weight = 10 },
      { name = "প্রজেক্ট", url = "/bn/projects/", weight = 20 },
      { name = "আমার সম্পর্কে", url = "/bn/about/", weight = 30 }
    ]}
